# file handling in python
f=open("02.txt","w")
print("File Name:",f.name)
print("File Mode:",f.mode)
print("IS File readable:",f.readable())
print("IS File Writable:",f.writable())
print("Is File closed:",f.closed)
# f.close()
# print("Is file closed",f.closed)
f.write("Welcome\n")
f.write("to\n")
f.write("the\n")
f.write("python world\n")
print("Data written to 02.txt  file successfully")
f.close()

f=open("01.txt","w")
f.write("Welcome to the python world\nWelcome to python programming")
print("Data written to the 01.txt file successfully")
f.close()

f=open("02.txt","a")
f.write("This is file handling in python ")
print("Data appended in 02.txt")
f.close()